/**
 * Turns the master JPEGs in src/assets/images into the responsive AVIF/WebP variants the site
 * actually ships, plus the Open Graph preview image.
 *
 * Nothing it writes is committed: the masters are the source of truth and everything here is
 * regenerated by `npm run images`, which `predev`, `prelint` and `prebuild` run for you. Each
 * output records what it was built from, so a rerun only re-encodes what actually changed.
 */
import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MASTERS = path.join(ROOT, 'src/assets/images');
const OUT = path.join(MASTERS, 'optimized');
const MODULE = path.join(ROOT, 'src/data/generatedImages.ts');
const OG_IMAGE = path.join(ROOT, 'public/og-image.jpg');

// Widths that matter for this layout: phone, tablet/half-column, and full-width hero.
const WIDTHS = [640, 1024, 1536];
const FALLBACK_WIDTH = 1024;
const OG = { width: 1200, height: 630, source: 'courtyard' };
const MANIFEST = path.join(OUT, '.manifest.json');

/** shorashim_kitchen_island_1788698669368.jpg -> kitchen_island */
const keyOf = (file) => path.parse(file).name.replace(/^shorashim_/, '').replace(/_\d+$/, '');

/**
 * What an output was built from: the master's bytes and the settings used. Content rather than
 * timestamps, so a CI cache restored with fresh mtimes is still recognised as up to date.
 */
const stampOf = (masterHash, settings) => createHash('sha1').update(masterHash).update(JSON.stringify(settings)).digest('hex').slice(0, 16);

async function main() {
  await fs.mkdir(OUT, { recursive: true });
  await fs.mkdir(path.dirname(OG_IMAGE), { recursive: true });
  const previous = JSON.parse(await fs.readFile(MANIFEST, 'utf8').catch(() => '{}'));
  const manifest = {};

  /** Rebuilds `out` unless an identical build of it is already on disk. */
  async function build(out, stamp, make) {
    manifest[path.basename(out)] = stamp;
    const exists = await fs.stat(out).then(() => true, () => false);
    if (exists && previous[path.basename(out)] === stamp) return false;
    await make();
    return true;
  }

  const masters = (await fs.readdir(MASTERS)).filter((f) => /\.jpe?g$/i.test(f)).sort();
  if (!masters.length) throw new Error(`no master images in ${MASTERS}`);

  const images = [];
  let written = 0;

  for (const file of masters) {
    const master = path.join(MASTERS, file);
    const masterHash = createHash('sha1').update(await fs.readFile(master)).digest('hex');
    const meta = await sharp(master).metadata();
    const key = keyOf(file);
    const widths = [...new Set(WIDTHS.map((w) => Math.min(w, meta.width)))].sort((a, b) => a - b);
    const entry = { key, width: meta.width, height: meta.height, avif: [], webp: [], fallback: '' };

    for (const width of widths) {
      for (const [format, options] of [
        ['avif', { quality: 50, effort: 6 }],
        ['webp', { quality: 75 }],
      ]) {
        const name = `${key}-${width}.${format}`;
        const out = path.join(OUT, name);
        const made = await build(out, stampOf(masterHash, { format, width, options }), () =>
          sharp(master).resize({ width, withoutEnlargement: true })[format](options).toFile(out)
        );
        if (made) written++;
        entry[format].push({ name, width });
      }
    }

    // One JPEG so browsers without AVIF or WebP still get a picture.
    const fallbackWidth = Math.min(FALLBACK_WIDTH, meta.width);
    const fallbackName = `${key}-${fallbackWidth}.jpg`;
    const fallbackPath = path.join(OUT, fallbackName);
    const fallbackOptions = { quality: 80, mozjpeg: true };
    if (await build(fallbackPath, stampOf(masterHash, { format: 'jpeg', width: fallbackWidth, options: fallbackOptions }), () =>
      sharp(master).resize({ width: fallbackWidth, withoutEnlargement: true }).jpeg(fallbackOptions).toFile(fallbackPath)
    )) {
      written++;
    }
    entry.fallback = fallbackName;
    images.push(entry);

    if (key === OG.source) {
      // Named separately in the manifest: it lives in public/, not next to the other outputs.
      const made = await build(OG_IMAGE, stampOf(masterHash, { og: OG }), () =>
        sharp(master).resize({ width: OG.width, height: OG.height, fit: 'cover' }).jpeg({ quality: 82, mozjpeg: true }).toFile(OG_IMAGE)
      );
      if (made) written++;
    }
  }

  const ident = (name) => 'img_' + name.replace(/[^a-z0-9]/gi, '_');
  const lines = ['// Generated by scripts/optimize-images.mjs. Do not edit; run `npm run images`.', "import type { ResponsiveImage } from '../types';", ''];
  const files = [...new Set(images.flatMap((i) => [...i.avif, ...i.webp].map((v) => v.name).concat(i.fallback)))];
  for (const name of files) lines.push(`import ${ident(name)} from '../assets/images/optimized/${name}';`);
  lines.push('', 'export const GENERATED_IMAGES = {');
  for (const image of images) {
    const srcset = (variants) => variants.map((v) => `\${${ident(v.name)}} ${v.width}w`).join(', ');
    lines.push(`  ${image.key}: {`);
    lines.push(`    avif: \`${srcset(image.avif)}\`,`);
    lines.push(`    webp: \`${srcset(image.webp)}\`,`);
    lines.push(`    fallback: ${ident(image.fallback)},`);
    lines.push(`    width: ${image.width},`);
    lines.push(`    height: ${image.height},`);
    lines.push('  },');
  }
  lines.push('} satisfies Record<string, ResponsiveImage>;', '');

  const next = lines.join('\n');
  const current = await fs.readFile(MODULE, 'utf8').catch(() => '');
  if (createHash('sha1').update(next).digest('hex') !== createHash('sha1').update(current).digest('hex')) {
    await fs.writeFile(MODULE, next);
  }
  await fs.writeFile(MANIFEST, JSON.stringify(manifest, null, 2) + '\n');
  console.log(`images: ${images.length} masters, ${files.length} variants (${written} written this run)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
