#!/usr/bin/env python3
"""Push apps-script/ to the Shorashim Apps Script project and point the web app deployment at it.

Usage: python3 apps-script/deploy.py [--content-only] ["description"]

--content-only updates the project code without releasing it to the web app. Use it before
adding OAuth scopes: the owner authorizes them by running `setup` in the editor, and only then
is the new version released, so the live web app never runs with unauthorized scopes.

IDs and secrets live in ~/.config/gcloud/shorashim/booking-config.json, never in this public
repo. They are written into a generated Config.js file that exists only inside the Apps Script
project. The first run creates the project and a web app deployment whose URL then stays fixed.
"""
import json
import pathlib
import sys

from google.auth.transport.requests import AuthorizedSession, Request
from google.oauth2.credentials import Credentials

HERE = pathlib.Path(__file__).resolve().parent
CRED_DIR = pathlib.Path.home() / ".config/gcloud/shorashim"
CONFIG_PATH = CRED_DIR / "booking-config.json"
API = "https://script.googleapis.com/v1"
CONFIG_KEYS = ("calendars", "hmacSecret", "ownerEmail", "webAppUrl", "recaptchaSecret", "adminSheetId", "availabilitySheetId")


def session():
    creds = Credentials.from_authorized_user_file(str(CRED_DIR / "token.json"))
    creds.refresh(Request())
    return AuthorizedSession(creds)


def call(s, method, url, **kwargs):
    r = s.request(method, url, **kwargs)
    if not r.ok:
        sys.exit(f"{method} {url} -> {r.status_code}: {r.text[:800]}")
    return r.json()


def save(cfg):
    CONFIG_PATH.write_text(json.dumps(cfg, indent=2, ensure_ascii=False))
    CONFIG_PATH.chmod(0o600)


def project_files(cfg):
    files = [{"name": "appsscript", "type": "JSON", "source": (HERE / "appsscript.json").read_text()}]
    for path in sorted((HERE / "src").iterdir()):
        kind = {".js": "SERVER_JS", ".html": "HTML"}.get(path.suffix)
        if kind:
            files.append({"name": path.stem, "type": kind, "source": path.read_text()})
    config = {key: cfg.get(key, "") for key in CONFIG_KEYS}
    source = "// Generated by deploy.py. Do not edit.\nvar CONFIG = " + json.dumps(config, indent=2, ensure_ascii=False) + ";\n"
    files.append({"name": "Config", "type": "SERVER_JS", "source": source})
    return files


def push_version(s, cfg, description):
    script = f"{API}/projects/{cfg['scriptId']}"
    call(s, "PUT", f"{script}/content", json={"files": project_files(cfg)})
    return call(s, "POST", f"{script}/versions", json={"description": description})["versionNumber"]


def main():
    args = sys.argv[1:]
    content_only = "--content-only" in args
    args = [a for a in args if a != "--content-only"]
    description = args[0] if args else "deploy"
    cfg = json.loads(CONFIG_PATH.read_text())
    s = session()

    if not cfg.get("scriptId"):
        cfg["scriptId"] = call(s, "POST", f"{API}/projects", json={"title": "Shorashim Booking"})["scriptId"]
        save(cfg)

    if not cfg.get("deploymentId"):
        version = push_version(s, cfg, "initial")
        dep = call(
            s,
            "POST",
            f"{API}/projects/{cfg['scriptId']}/deployments",
            json={"versionNumber": version, "manifestFileName": "appsscript", "description": "web app"},
        )
        cfg["deploymentId"] = dep["deploymentId"]
        cfg["webAppUrl"] = next(
            (p["webApp"]["url"] for p in dep.get("entryPoints", []) if "webApp" in p),
            f"https://script.google.com/macros/s/{dep['deploymentId']}/exec",
        )
        save(cfg)

    if content_only:
        call(s, "PUT", f"{API}/projects/{cfg['scriptId']}/content", json={"files": project_files(cfg)})
        print("Updated project code only (not released to the web app).")
        print(f"Editor:  https://script.google.com/d/{cfg['scriptId']}/edit")
        return

    version = push_version(s, cfg, description)
    call(
        s,
        "PUT",
        f"{API}/projects/{cfg['scriptId']}/deployments/{cfg['deploymentId']}",
        json={
            "deploymentConfig": {
                "scriptId": cfg["scriptId"],
                "versionNumber": version,
                "manifestFileName": "appsscript",
                "description": description,
            }
        },
    )
    print(f"Deployed version {version}")
    print(f"Web app: {cfg['webAppUrl']}")
    print(f"Editor:  https://script.google.com/d/{cfg['scriptId']}/edit")


if __name__ == "__main__":
    main()
